config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "users#home"
  resources :search, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/models/book_category.rb
class BookCategory < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @categories = Category.all
    @params = params[:q]
    @q = Book.ransack(params[:q])
    @books = @q.result(distinct: true)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tiphon</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/search/index.html.erb
<h2>検索画面</h2>

<%= search_form_for @q, url: search_index_path do |f| %>
  <%= f.label :title_cont, "タイトル" %>
  <%= f.search_field :title_cont %>
  <br>
  <%= f.label :book_category_id_in, "カテゴリ" %>
  <%- @categories.each_with_index do |category, i| %>
    <%= f.check_box :book_category_id_in, {multiple: true, include_hidden: false, class: 'list'}, i+1 %>
    <%= category.name %>
  <% end %>
  <br>
  <%= f.submit "検索" %>
<% end %>

<% if @params.present? %>
  <h2>検索結果</h2> 
  <%- @books.each do |book| %>
  <%= book.title %><br>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
    <div class="py-4 bg-dark fixed-bottom">
        <p class="text-white text-center">© Copyrights Z-antiphon All Rights Reserved</p>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 bg-dark py-3 d-flex">
                <div class="header-logo col-6 d-flex justify-content-start">
                    <img src="assets/zanti.png" style="width:100px; height: 100px;">
                </div>
                <div class="header-menu col-6 d-flex justify-content-end pt-4">
                    <a class="menu-trigger" href="#">
                        <span></span>
                        <span></span>
                        <span></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</header>

app/views/users/home.html.erb
<p>Tsukantiphon</p>